# permissions for end users to edit glotpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glotpod-editor-role
rules:
- apiGroups:
  - goglot.dev.github.com
  resources:
  - glotpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goglot.dev.github.com
  resources:
  - glotpods/status
  verbs:
  - get
